% Love
understandable(love).
understandable(lust).
understandable(liking).
understandable(caring).
understandable(passion).
understandable(fondness).
understandable(affection).
understandable(attraction).
understandable(tenderness).
understandable(compassion).
understandable(infatuation).
understandable(sentimentality).

% Joy
understandable(joy).
understandable(glee).
understandable(zest).
understandable(zeal).
understandable(hope).
understandable(pride).
understandable(thrill).
understandable(gaiety).
understandable(relief).
understandable(triumph).
understandable(elation).
understandable(delight).
understandable(rapture).
understandable(ecstasy).
understandable(longing).
understandable(optimism).
understandable(pleasure).
understandable(euphoria).
understandable(gladness).
understandable(eagerness).
understandable(jolliness).
understandable(happiness).
understandable(enjoyment).
understandable(joviality).
understandable(jubilation).
understandable(excitement).
understandable(enthusiasm).
understandable(contentment).
understandable(cheerfulness).
understandable(satisfaction).
understandable(exhilaration).
understandable(enthrallment).

% Anger
understandable(rage).
understandable(fury).
understandable(hate).
understandable(wrath).
understandable(envy).
understandable(anger).
understandable(scorn).
understandable(spite).
understandable(dislike).
understandable(outrage).
understandable(torment).
understandable(disgust).
understandable(ferocity).
understandable(loathing).
understandable(jealousy).
understandable(contempt).
understandable(annoyance).
understandable(agitation).
understandable(revulsion).
understandable(hostility).
understandable(grumpiness).
understandable(irritation).
understandable(bitterness).
understandable(resentment).
understandable(grouchiness).
understandable(frustration).
understandable(aggravation).
understandable(vengefulness).
understandable(exasperation).

% Surprise
understandable(surprise).
understandable(amazement).
understandable(astonishment).

% Sadness
understandable(woe).
understandable(hurt).
understandable(agony).
understandable(guilt).
understandable(gloom).
understandable(shame).
understandable(grief).
understandable(tired).
understandable(misery).
understandable(regret).
understandable(dismay).
understandable(insult).
understandable(sorrow).
understandable(remorse).
understandable(sadness).
understandable(anguish).
understandable(despair).
understandable(neglect).
understandable(exhaust).
understandable(defeated).
understandable(glumness).
understandable(rejection).
understandable(isolation).
understandable(dejection).
understandable(suffering).
understandable(insecurity).
understandable(alienation).
understandable(loneliness).
understandable(melancholy).
understandable(depression).
understandable(humiliation).
understandable(unhappiness).
understandable(displeasure).
understandable(hopelessness).
understandable(homesickness).
understandable(embarrassment).
understandable(disappointment).

% Fear
understandable(fear).
understandable(pity).
understandable(alarm).
understandable(shock).
understandable(panic).
understandable(dread).
understandable(worry).
understandable(fright).
understandable(terror).
understandable(horror).
understandable(anxiety).
understandable(distress).
understandable(hysteria).
understandable(sympathy).
understandable(tenseness).
understandable(uneasiness).
understandable(nervousness).
understandable(apprehension).
